### ISSUE TITLE
[Q] Range and tests

### ISSUE THREAD

**Issue by rsurgiewicz** [ronnythomas/Zigbee-3-Stick-CC2538-2592#2]
Hello,

I'm looking for some zigbee coordinator (to be used with zigbee2mqtt) with better reciption range than CC2530 or 31.
I've tried some antenna mods but still it does not perform well.

What are Your impressions after testing your Zigbee-3-Stick-CC2538-2592 device?
Is the range any better?

Is it possible to purchase 1 device for testing purposes?

Thank You

**Comment by ronnythomas** [comment]
https://forum.iobroker.net/topic/30609/cc2538-cc2592-pa-zigbee-stick-platine
